// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CIPluginHost.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace BBI.Common.Protobuf.PluginHost {
  public static partial class CIPluginHost
  {
    static readonly string __ServiceName = "BBI.Protobuf.Hosts.CIPluginHost";

    static readonly grpc::Marshaller<global::BBI.Common.Protobuf.PluginRegistration> __Marshaller_PluginRegistration = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::BBI.Common.Protobuf.PluginRegistration.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::BBI.Common.Protobuf.PluginRegistrationReply> __Marshaller_PluginRegistrationReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::BBI.Common.Protobuf.PluginRegistrationReply.Parser.ParseFrom);

    static readonly grpc::Method<global::BBI.Common.Protobuf.PluginRegistration, global::BBI.Common.Protobuf.PluginRegistrationReply> __Method_Register = new grpc::Method<global::BBI.Common.Protobuf.PluginRegistration, global::BBI.Common.Protobuf.PluginRegistrationReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Register",
        __Marshaller_PluginRegistration,
        __Marshaller_PluginRegistrationReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::BBI.Common.Protobuf.PluginHost.CIPluginHostReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CIPluginHost</summary>
    public abstract partial class CIPluginHostBase
    {
      public virtual global::System.Threading.Tasks.Task<global::BBI.Common.Protobuf.PluginRegistrationReply> Register(global::BBI.Common.Protobuf.PluginRegistration request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CIPluginHost</summary>
    public partial class CIPluginHostClient : grpc::ClientBase<CIPluginHostClient>
    {
      /// <summary>Creates a new client for CIPluginHost</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CIPluginHostClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CIPluginHost that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CIPluginHostClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CIPluginHostClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CIPluginHostClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::BBI.Common.Protobuf.PluginRegistrationReply Register(global::BBI.Common.Protobuf.PluginRegistration request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Register(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::BBI.Common.Protobuf.PluginRegistrationReply Register(global::BBI.Common.Protobuf.PluginRegistration request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Register, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::BBI.Common.Protobuf.PluginRegistrationReply> RegisterAsync(global::BBI.Common.Protobuf.PluginRegistration request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RegisterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::BBI.Common.Protobuf.PluginRegistrationReply> RegisterAsync(global::BBI.Common.Protobuf.PluginRegistration request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Register, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CIPluginHostClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CIPluginHostClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CIPluginHostBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Register, serviceImpl.Register).Build();
    }

  }
}
#endregion
