// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CIPluginHost.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BBI.Common.Protobuf.PluginHost {

  /// <summary>Holder for reflection information generated from CIPluginHost.proto</summary>
  public static partial class CIPluginHostReflection {

    #region Descriptor
    /// <summary>File descriptor for CIPluginHost.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CIPluginHostReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJDSVBsdWdpbkhvc3QucHJvdG8SEkJCSS5Qcm90b2J1Zi5Ib3N0cxoUUGx1",
            "Z2luTWVzc2FnZXMucHJvdG8yZQoMQ0lQbHVnaW5Ib3N0ElUKCFJlZ2lzdGVy",
            "EiAuQkJJLlByb3RvYnVmLlBsdWdpblJlZ2lzdHJhdGlvbholLkJCSS5Qcm90",
            "b2J1Zi5QbHVnaW5SZWdpc3RyYXRpb25SZXBseSIAQiGqAh5CQkkuQ29tbW9u",
            "LlByb3RvYnVmLlBsdWdpbkhvc3RiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BBI.Common.Protobuf.PluginMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
