// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PluginMessages.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BBI.Common.Protobuf {

  /// <summary>Holder for reflection information generated from PluginMessages.proto</summary>
  public static partial class PluginMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for PluginMessages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PluginMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQbHVnaW5NZXNzYWdlcy5wcm90bxIMQkJJLlByb3RvYnVmIm0KCUNJUmVx",
            "dWVzdBIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCRIOCgZ1",
            "c2VTU0wYAyABKAgSHAoUYnVpbGRDb25maWd1cmF0aW9uSWQYBCABKAkSDgoG",
            "YnJhbmNoGAUgASgJIm0KCkNJUmVzcG9uc2USNQoEdHlwZRgBIAEoDjInLkJC",
            "SS5Qcm90b2J1Zi5DSVJlc3BvbnNlLkNJUmVzcG9uc2VUeXBlIigKDkNJUmVz",
            "cG9uc2VUeXBlEgsKB1NVQ0NFU1MQABIJCgVFUlJPUhABIigKElBsdWdpblJl",
            "Z2lzdHJhdGlvbhISCgpwbHVnaW5OYW1lGAEgASgJIhkKF1BsdWdpblJlZ2lz",
            "dHJhdGlvblJlcGx5QhaqAhNCQkkuQ29tbW9uLlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BBI.Common.Protobuf.CIRequest), global::BBI.Common.Protobuf.CIRequest.Parser, new[]{ "Username", "Password", "UseSSL", "BuildConfigurationId", "Branch" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::BBI.Common.Protobuf.CIResponse), global::BBI.Common.Protobuf.CIResponse.Parser, new[]{ "Type" }, null, new[]{ typeof(global::BBI.Common.Protobuf.CIResponse.Types.CIResponseType) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::BBI.Common.Protobuf.PluginRegistration), global::BBI.Common.Protobuf.PluginRegistration.Parser, new[]{ "PluginName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::BBI.Common.Protobuf.PluginRegistrationReply), global::BBI.Common.Protobuf.PluginRegistrationReply.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CIRequest : pb::IMessage<CIRequest> {
    private static readonly pb::MessageParser<CIRequest> _parser = new pb::MessageParser<CIRequest>(() => new CIRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CIRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BBI.Common.Protobuf.PluginMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CIRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CIRequest(CIRequest other) : this() {
      username_ = other.username_;
      password_ = other.password_;
      useSSL_ = other.useSSL_;
      buildConfigurationId_ = other.buildConfigurationId_;
      branch_ = other.branch_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CIRequest Clone() {
      return new CIRequest(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "useSSL" field.</summary>
    public const int UseSSLFieldNumber = 3;
    private bool useSSL_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool UseSSL {
      get { return useSSL_; }
      set {
        useSSL_ = value;
      }
    }

    /// <summary>Field number for the "buildConfigurationId" field.</summary>
    public const int BuildConfigurationIdFieldNumber = 4;
    private string buildConfigurationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BuildConfigurationId {
      get { return buildConfigurationId_; }
      set {
        buildConfigurationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "branch" field.</summary>
    public const int BranchFieldNumber = 5;
    private string branch_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Branch {
      get { return branch_; }
      set {
        branch_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CIRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CIRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      if (UseSSL != other.UseSSL) return false;
      if (BuildConfigurationId != other.BuildConfigurationId) return false;
      if (Branch != other.Branch) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (UseSSL != false) hash ^= UseSSL.GetHashCode();
      if (BuildConfigurationId.Length != 0) hash ^= BuildConfigurationId.GetHashCode();
      if (Branch.Length != 0) hash ^= Branch.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (UseSSL != false) {
        output.WriteRawTag(24);
        output.WriteBool(UseSSL);
      }
      if (BuildConfigurationId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(BuildConfigurationId);
      }
      if (Branch.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Branch);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (UseSSL != false) {
        size += 1 + 1;
      }
      if (BuildConfigurationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BuildConfigurationId);
      }
      if (Branch.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Branch);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CIRequest other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.UseSSL != false) {
        UseSSL = other.UseSSL;
      }
      if (other.BuildConfigurationId.Length != 0) {
        BuildConfigurationId = other.BuildConfigurationId;
      }
      if (other.Branch.Length != 0) {
        Branch = other.Branch;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 24: {
            UseSSL = input.ReadBool();
            break;
          }
          case 34: {
            BuildConfigurationId = input.ReadString();
            break;
          }
          case 42: {
            Branch = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CIResponse : pb::IMessage<CIResponse> {
    private static readonly pb::MessageParser<CIResponse> _parser = new pb::MessageParser<CIResponse>(() => new CIResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CIResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BBI.Common.Protobuf.PluginMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CIResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CIResponse(CIResponse other) : this() {
      type_ = other.type_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CIResponse Clone() {
      return new CIResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::BBI.Common.Protobuf.CIResponse.Types.CIResponseType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BBI.Common.Protobuf.CIResponse.Types.CIResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CIResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CIResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CIResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::BBI.Common.Protobuf.CIResponse.Types.CIResponseType) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the CIResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum CIResponseType {
        [pbr::OriginalName("SUCCESS")] Success = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
      }

    }
    #endregion

  }

  public sealed partial class PluginRegistration : pb::IMessage<PluginRegistration> {
    private static readonly pb::MessageParser<PluginRegistration> _parser = new pb::MessageParser<PluginRegistration>(() => new PluginRegistration());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PluginRegistration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BBI.Common.Protobuf.PluginMessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PluginRegistration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PluginRegistration(PluginRegistration other) : this() {
      pluginName_ = other.pluginName_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PluginRegistration Clone() {
      return new PluginRegistration(this);
    }

    /// <summary>Field number for the "pluginName" field.</summary>
    public const int PluginNameFieldNumber = 1;
    private string pluginName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PluginName {
      get { return pluginName_; }
      set {
        pluginName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PluginRegistration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PluginRegistration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PluginName != other.PluginName) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PluginName.Length != 0) hash ^= PluginName.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PluginName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PluginName);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PluginName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PluginName);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PluginRegistration other) {
      if (other == null) {
        return;
      }
      if (other.PluginName.Length != 0) {
        PluginName = other.PluginName;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            PluginName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PluginRegistrationReply : pb::IMessage<PluginRegistrationReply> {
    private static readonly pb::MessageParser<PluginRegistrationReply> _parser = new pb::MessageParser<PluginRegistrationReply>(() => new PluginRegistrationReply());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PluginRegistrationReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BBI.Common.Protobuf.PluginMessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PluginRegistrationReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PluginRegistrationReply(PluginRegistrationReply other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PluginRegistrationReply Clone() {
      return new PluginRegistrationReply(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PluginRegistrationReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PluginRegistrationReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PluginRegistrationReply other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
