// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CIPlugin.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BBI.Common.Protobuf.Plugin {

  /// <summary>Holder for reflection information generated from CIPlugin.proto</summary>
  public static partial class CIPluginReflection {

    #region Descriptor
    /// <summary>File descriptor for CIPlugin.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CIPluginReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5DSVBsdWdpbi5wcm90bxISQkJJLlByb3RvYnVmLkhvc3RzGhRQbHVnaW5N",
            "ZXNzYWdlcy5wcm90bzKKAQoIQ0lQbHVnaW4SRgoPR2V0Q3VycmVudFN0YXRl",
            "EhcuQkJJLlByb3RvYnVmLkNJUmVxdWVzdBoYLkJCSS5Qcm90b2J1Zi5DSVJl",
            "c3BvbnNlIgASNgoIU2h1dGRvd24SEy5CQkkuUHJvdG9idWYuRW1wdHkaEy5C",
            "QkkuUHJvdG9idWYuRW1wdHkiAEIdqgIaQkJJLkNvbW1vbi5Qcm90b2J1Zi5Q",
            "bHVnaW5iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BBI.Common.Protobuf.PluginMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
